### ISSUE TITLE
No resource identifier found for attribute 'appComponentFactory' in package 'android' after library linking

### ISSUE THREAD

**Issue by indapublic** [rumax/react-native-PDFView#77] opened 2018-10-05 00:42 UTC
Cannot build android app after linking library.

1. App has been built succesfully.

2. Add library:
```
Open up android/app/src/main/java/[...]/MainApplication.java
Add import com.rumax.reactnative.pdfviewer.PDFViewPackage; to the imports at the top of the file
Add new PDFViewPackage() to the list returned by the getPackages() method
Append the following lines to android/settings.gradle:
include ':react-native-view-pdf'
project(':react-native-view-pdf').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-view-pdf/android')
Insert the following lines inside the dependencies block in android/app/build.gradle:
compile project(':react-native-view-pdf')
```

3. Trying to build app again and receive error:

```
/android/app/build/intermediates/manifests/full/debug/AndroidManifest.xml:61: AAPT: No resource identifier found for attribute 'appComponentFactory' in package 'android'

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> Failed to process resources, see aapt output above for details.
```

Don't have necessary experience for resolving that, so I need your help at the moment

**Comment by rumax** [comment] 2018-10-06 05:52
I would suggest you to try to reproduce the issue in demo project. Or create a simple project where it can be reproduced.

Otherwise we need the content of the AndroidManifest.xml, gradle files you use and more output from gradle.

**Comment by rumax** [comment] 2018-10-16 19:49
Closing since no additional information is provided. Please, reopen with additional information if it's still actual.

**Closed by rumax** 2018-10-16 19:49 UTC
Labels: help wanted, question
